services:
  server:
    build:
      context: .
      target: final
    ports:
      - 80:80
    environment:
      - REDIS_SERVER_HOSTNAME=redis
      - REDIS_SERVER_PORT=6379
      - WEBSOCKET_PORT=3000
      - WEBSOCKET_ADDR=[::]
    depends_on:
      - redis
  redis:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
    volumes:
      - ./docker_data/redis:/data
