services:
  nginx_proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./docker_data/nginx:/var/log/nginx
    depends_on:
      - webserver
      - api
      - websocket
    # DEBUG: sleep
    command: [ "sleep", "100000" ]

  webserver:
    build:
      context: .
      target: final
    environment:
      - WEBSERVER_PORT=3000
      - WEBSERVER_HOST=[::]
    depends_on:
      - redis
      - api

    volumes:
      - ./static:/static:ro
    command: [ "/bin/server", "webserver" ]

  api:
    build:
      context: .
      target: final
    environment:
      - REDIS_SERVER_HOSTNAME=redis
      - REDIS_SERVER_PORT=6379
      - API_PORT=3000
      - API_HOST=[::]
    depends_on:
      - redis
    command: [ "/bin/server", "api" ]

  websocket:
    build:
      context: .
      target: final
    environment:
      - REDIS_SERVER_HOSTNAME=redis
      - REDIS_SERVER_PORT=6379
      - WEBSOCKET_PORT=3000
      - WEBSOCKET_HOST=[::]
    depends_on:
      - redis
    command: [ "/bin/server", "websocket" ]

  redis:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
    volumes:
      - ./docker_data/redis:/data
